services:
  web:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env.sample
    networks:
      - postgres
      - redis
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    env_file:
      - .env.sample
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis

volumes:
  pg_data:

networks:
  redis:
    driver: bridge
  postgres:
    driver: bridge